### ISSUE TITLE
Accidental argument

### ISSUE THREAD

**Issue by keizer7** [hanruihua/rl_rvo_nav#14]
Hello author, may I ask that TypeError occurs when I run train_process for the first time: make() got an unexpected keyword argument 'world_name', of course, the following parameters are also redundant, I am a novice, hope the author can help point out

**Comment by keizer7** [comment]
Then I got ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError('')) 
Try one of the following resolutions: 
* Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

**Comment by hanruihua** [comment]
Hi,

For the first poroblem, it may be caused by the version of gym, please try to install the older version.

For the second problem, the most likely cause is the package pynput. you can reinstall or test this package Individually, or comment out the import code, which does not influences the functionality of the project.
