### ISSUE TITLE
新入坑的学生 求指点

### ISSUE THREAD

**Issue by ncepu666** [hanruihua/rl_rvo_nav#21]
Traceback (most recent call last):
  File "D:\AAAWork\old_test\rl_rvo_nav-main\rl_rvo_nav-main\rl_rvo_nav\pre_trained_model\policy_test_pre_train.py", line 6, in <module>
    from rl_rvo_nav.policy_test.post_train import post_train
ModuleNotFoundError: No module named 'rl_rvo_nav'，遇到了这个问题 在运行三个train process 和预训练文件都会报这个错误 不知道该怎么解决 可能有点弱智，麻烦您了

**Comment by hanruihua** [comment]
你好，

这个错误是因为rl_rvo_nav没有安装，需要在 rl_rvo_nav 目录下，运行 ./setup.sh， 才会把包的路径安装到python库中, 或者单独运行 setup.sh 里的命令

Translated:

This error is because rl_rvo_nav is not installed. You need to run ./setup.sh in the rl_rvo_nav directory to install the package path into the python library, or run the commands in setup.sh separately.
